### ISSUE TITLE
Review the `key_protect_instance_policies` output

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-kms-all-inclusive#417]
Seems a little odd?
```
key_protect_instance_policies = {
  "dual_auth_delete" = tolist([])
  "id" = "crn:v1:bluemix:public:kms:us-south:a/abac0df06b644a9cabc6e44f55b3880e:4d20584d-7917-4f56-8767-8bf1cc7f4609::"
  "instance_id" = "4d20584d-7917-4f56-8767-8bf1cc7f4609"
  "key_create_import_access" = tolist([])
  "metrics" = tolist([])
  "rotation" = tolist([])
  "timeouts" = null /* object */
}
```

**Comment by MatthewLemmond** [comment]
@ocofaigh This is a problem with the output from the provider, it's being passed through without any changes at the key protect module: https://github.com/terraform-ibm-modules/terraform-ibm-key-protect/blob/main/outputs.tf#L21

I have a workaround to clean it up that we can use for now, but this will need to be addressed with an issue to the provider team.

**Comment by MatthewLemmond** [comment]
Created issue with provider for output fields not matching what's expected, linked above

**Comment by ocofaigh** [comment]
This issue was fixed in https://github.com/terraform-ibm-modules/terraform-ibm-key-protect/pull/534 and this version is now in the KMS all inc module - closing
