### ISSUE TITLE
papercut: keys input description

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-kms-all-inclusive#440]
https://github.com/terraform-ibm-modules/terraform-ibm-kms-all-inclusive/blob/754931d48f5f7c748b774f345e1f0364a87e8026/solutions/standard/variables.tf#L87

Description should include a link to the format of the input variable. Currently from the IBM Cloud interface it is not possible to figure out how to pass a list of keys to create.

**Comment by shemau** [comment]
Resolved in v4.11.3
