### ISSUE TITLE
papercut: drop down list for service_endpoints

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-kms-all-inclusive#443]
### Description

This should be doable by explicitly inputing options in the ibm_catalog.json

see example: https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/blob/b2a2bea04930ad8bd3f7ee2010f29d194ce005d7/ibm_catalog.json#L206

**Comment by iamar7** [comment]
PR Merged
