### ISSUE TITLE
Expose `rotation_interval_month` in KMS DA and default it to "12"

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-kms-all-inclusive#478]
Relevant code: https://github.com/terraform-ibm-modules/terraform-ibm-kms-all-inclusive/blob/d1495563e20394125742bae7b0fe59501d95f47a/solutions/standard/main.tf#L31

Expose `rotation_interval_month` in KMS DA as a variable and default it to "12"

**Comment by alex-reiff** [comment]
PR merged, closing
